CREATE TABLE `user` (
  `id` varchar(64) NOT NULL DEFAULT '',
  `screenName` varchar(256) DEFAULT NULL,
  `name` varchar(256) DEFAULT NULL,
  `province` varchar(64) DEFAULT NULL,
  `city` varchar(64) DEFAULT NULL,
  `location` varchar(2048) DEFAULT NULL,
  `description` varchar(2048) DEFAULT NULL,
  `url` varchar(2048) DEFAULT NULL,
  `profileImageUrl` varchar(2048) DEFAULT NULL,
  `userDomain` varchar(2048) DEFAULT NULL,
  `gender` varchar(64) DEFAULT NULL,
  `followersCount` int(11) DEFAULT NULL,
  `friendsCount` int(11) DEFAULT NULL,
  `statusesCount` int(11) DEFAULT NULL,
  `favoritesCount` int(11) DEFAULT NULL,
  `createdAt` datetime DEFAULT NULL,
  `verified` int(11) DEFAULT NULL,
  `verifiedType` int(11) DEFAULT NULL,
  `verifiedReason` varchar(2048) DEFAULT NULL,
  `allowAllActMsg` int(11) DEFAULT NULL,
  `allowAllComment` int(11) DEFAULT NULL,
  `avatarLarge` varchar(2048) DEFAULT NULL,
  `biFollowersCount` int(11) DEFAULT NULL,
  `lang` varchar(64) DEFAULT NULL,
  `weihao` varchar(64) DEFAULT NULL,
  `refreshTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
